config/routes.rb
Rails.application.routes.draw do
  root 'shorteners#index'

  post '/'     => 'shorteners#create'
  get  '/:key' => 'shorteners#show', as: :shortened
end

app/models/random_key.rb
module RandomKey
  CHAR_SET = Array('A'..'Z') +
             Array('a'..'z') +
             Array('0'..'9')

  CHAR_LENGTH = 6

  def self.generate(length = CHAR_LENGTH)
    CHAR_SET.sample(length).join
  end
end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :url, format: { with: URI::regexp }

  def self.find_or_create_unique(url)
    find_by(url: url) ||
    create(key: RandomKey.generate, url: url)
  rescue ActiveRecord::RecordNotUnique
    find_or_create_unique(url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  def index
    @url = Url.new
  end

  def create
    @url = Url.new
    @generated_url = Url.find_or_create_unique params_url[:url]

    render :index
  end

  def show
    url = Url.find_by! key: params[:key]

    redirect_to url.url
  end

  private
    def params_url
      params.require(:url)
            .permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortenerUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/shorteners/index.html.erb
<div id='main-interface'>
  <div class='row'>
    <div class='col-xs-12'>
      <% if @generated_url %>
        <% if @generated_url.errors.any? %>
          <%= @generated_url.errors.full_messages.join() %>
        <% else %>
          <% url = shortened_url(key: @generated_url.key) %>
          <%= link_to url, url, target: '_blank' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12'>
      <%= form_for @url, url: '/', html: { class: 'form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :url %>: &nbsp;
          <%= f.text_field :url, class: 'form-control' %>
        </div>
      <% end %>
    </div>
  </div>
</div>